### ISSUE TITLE
Early view - working on frontend

### ISSUE THREAD

**Issue by defiancecp** [gtbikev/courses#26]
Just wanted to share some work I've been slowly chipping away at for the past couple days.  Basically, it's intended to be a site to serve as a user-friendly frontend for course info/download/etc.  

Here's what it looks like right now:
https://www.gtbikevroutes.fun/RouteTable.php

Basically, currently consists of a hosted mysql db with a php script to capture the routes detail from the readme on your routes project (run via cron job and updating every 30 minutes), and a rough functional outline for how the frontend browsing experience might work.    Browsing experience right now is *completely* unformatted, but imports data, shows the user a routes listing with summary info, allows user toggle between metric & imperial (note that defaults are metric, and imperial is not based on the imported value- it's calculated based on metric), includes links to download, show map, or go into more detailed view, and the detailed view is in place as well (though right now it doesn't actually show details :P ).  Probably the most key functionality this adds, though, is the user submitted ratings - shown on all routes, and each click records a rating - rating aggregation is based on most recent submission from any given IP on any given route, so no user logins are needed.  Could be spoofed to manipulate the rankings, but I'm thinking the value of having a login-free experience is greater than protecting from vote manipulation :)

It's still a long way from actually shareable, but wanted to give you a preview since it's atop your repository, and you might have feedback.

Current planned incoming changes:
-FORMATTING - so ugly now :P 
-Add all the basic information needed for this type of site (links to sources, credit, mod project, git page, so on so on)
-Add sorting and filtering to table view
-Add description, map image, etc. to detailed page (thinking of using a double-row table: Row 1 will be all non-description data for the course, while row 2 would be a single-cell row with description, etc.
-Move the whole thing - db, php scripts, and website into a git repository.  Maybe look into some form of configurable managed deployment - right now it's manual file editing and copy/pasting :p 
-Setup backups and such

Some things that seem like they might be useful:
-I could shift how metadata is managed: instead of scraping from a formatted readme, I could update so that there's a web form for managing the metadata in the db, then I could provide you with a query to create a formatted table for readme with one click.  
-could pull the commit history and notes from github for each relevant file and show a changelog in the details page, maybe?
-Maybe add user comments associated with each route detail page?  But would have to moderate then, ugh :p 

Anyway, hope you find this interesting - Also apologize for opening an issue for this - fairly new to git (used VS repositories until moving to git-based VSO just recently - and VSO's version of a git interface is pretty different from Github :) ---  Guess I should break down and actually learn the command prompts! ), so not sure how else to drop a note related to the project :)

**Comment by murech** [comment]
@defiancecp wow, awesome and thanks for sharing! Let me know if you want a separate repository on this project. I can give you read/write access.

Regarding managed deployment: github allows to create pipelines. I planned to do this for this repository so releases (zip package) are automatically done. I will share the details once available.

I don't see the need for generating a readme. The approach of using a readme as data input is fine for a start but I suggest to just simplify the readme and use separate metadata to do this. This also allows greater flexibility for your route database changes.

The next version of route builder will have its own metadata (xml format) and you can save this file (.rdb). This will allow to store more route related metadata. The advantage of this approach is that you can extend the schema without impacting the course files. Moreover, course and map editor files will be generated from the metadata and metadata can be generated from map editor or course files. Finally, there will be an additional folder (metadata) in this repository for storing metadata files. So basically you could just read the metadata files from there.

I use visual studio code. It's the best universal code editor and git is build-in (command line or visually). Don't worry, communicating with issues is fine. Git was build for collaboration 😉.

**Comment by murech** [comment]
@defiancecp I'm closing this discussion for now since you released the initial version.
