### ISSUE TITLE
Windy Hills - trouble turn

### ISSUE THREAD

**Issue by defiancecp** [gtbikev/courses#28]
At around 2.1mi (~3.3km) from the start, there's a generally-downhill part where you can build up some speed, followed by a sharp turn and wayoint immediately after -- you can easily be going fast enough to overshoot the turn a bit.  It recovers OK, but by that time it's past the waypoint, so it loops back and does a little meandering. 

You can see it in my ride here: https://ridewithgps.com/trips/51488719 ...  The backtracking is minimal, and totaled up to about 0.1mi - so clearly non-critical.  Just might be a little smoother/more forgiving if the waypoint was moved a bit further after the turn, I think?

Loved the ride though, and even with that I'd say it was a successful test (using latest version)

**Comment by murech** [comment]
@defiancecp thanks for the feedback. I also noticed that since the latest mod release the waypoint are cleared earlier as before. I will have a look and provide an updated version.

**Comment by murech** [comment]
Hi @defiancecp 

This bug was fixed with version 19.0.
