### ISSUE TITLE
gravel_gravelfondo - trouble turn

### ISSUE THREAD

**Issue by oldnapalm** [gtbikev/courses#45]
Auto pilot takes a wrong turn at this waypoint, looks like it prefers a paved path to the next one.

![Captura de Tela 2020-08-03 às 10 25 39](https://user-images.githubusercontent.com/38410858/89189992-3083f400-d577-11ea-9acf-12f79585205b.png)

**Comment by murech** [comment]
Hi @oldnapalm 
I did not have an issue riding the course over 10 times. Can you please provide your testing setup? You find an example in the guidelines: https://github.com/gtbikev/courses#guidelines.

**Comment by oldnapalm** [comment]
Hi @murech 

I rode the course again and the problem did not happen, probably it was a random issue in the first ride.

Thanks for your attention.
