### ISSUE TITLE
Unable to start "Suburban Crit" course due to invisible barrier

### ISSUE THREAD

**Issue by strayduck** [gtbikev/courses#48]
After warping to the start of the "Suburban Crit" course my avatar is able to mount the bike and begins pedaling but the bike does not move forward. I've dismounted the bike and turned the steering left and right but that does not steer the avatar away from whatever has it 'stuck'.

The bike computer is showing input from my smart trainer and registering power and speed. 

There are no visible obstacles 

Running the latest Rockstar Games GTAV and GTBikeV mod in bootcamp on a 2018 Macbook Pro. Also have the latest version of Windows 10 available as of September 15.

**Comment by oldnapalm** [comment]
Are you using version 0.4.0.4 of the mod? I experienced this issue in version 0.4.0.3 but it was fixed in the latest release.

**Comment by strayduck** [comment]
Thanks oldnapalm, I believe so but just to be sure I'll re-download the mod and overwrite the existing files and test again.

**Comment by strayduck** [comment]
As a follow-up I checked my download folder and it looks like I had 0.4.0.2. Updating to 0.4.0.4 resolved the issue.
