### ISSUE TITLE
.json vs .fit file names

### ISSUE THREAD

**Issue by defiancecp** [gtbikev/courses#91]
We currently have 2 .fit files that mismatch the associated .json filenames.  Can we rename to align?  Files are:
3-tour-of-los-santos.fit
3-tour-los-santos.json
34-tracks-terminals-tarmac.fit
34-tracks-terminal-tarmac.json

Wasn't sure if the mod itself has dependencies on the existing filenames -- If so, it's probably easier to just update my db scripts to search by ID.  But if there's no dependency, just renaming the file so the names are the same except extensions would simplify things :)

**Comment by murech** [comment]
Thanks for the feedback. The files in the fit and course folder do not affect the mod. I will rename them.

**Comment by murech** [comment]
Hi @defiancecp. Files are renamed, api metadata file changed. Can you check and provide feedback?

**Comment by defiancecp** [comment]
Perfect, 100% course & preview load this time :)
