### ISSUE TITLE
The courses file should contain destinations for the new random destination feature

### ISSUE THREAD

**Issue by Makinolo** [gtbikev/courses#93]
Apart from the course data, a new section is needed called DestinationList that will contain destination coordinates and names for different parts of the map that will be used instead of the GTA V built in drive wander.
Attached is the current list of possible destinations inserted in the current version of the course.json

[courses .json.txt](https://github.com/gtbikev/courses/files/5986112/courses.json.txt)

**Comment by murech** [comment]
Implemented with version 21.0.
